### PR TITLE
Fieldstate constructor only accepts value

### PR DESCRIPTION
**Pull request by janpieterz**
Configuration for OnUpdate, Enable/Disable auto validation and the auto
validation debounce done through chained methods for FieldState.

Tests await slightly increased where applicable when slight timing
errors made tests fail falsely occasionally

### CODE REVIEW

**Comment by janpieterz** [comment]
Fixes #16

**Comment by janpieterz** [comment]
Let me know if you approve of the code change and I'll draft up a PR for the docs repository too to keep them in sync ;)

**Comment by basarat** [comment]
> Let me know if you approve of the code change and I'll draft up a PR for the docs repository too to keep them in sync ;)

Approved! Thanks a lot for this. I hated the inconsistency with `FormState` :) :rose: 

image
Always a good sign 👍 :heart:

**Comment by basarat** [comment]
Thanks! `0.18.0` :rose: :heart:

**Comment by janpieterz** [comment]
Glad I could help out!

**Pull request merged**
